### ISSUE TITLE
Unexpected string in standard-format/esformatter/rocambole/esprima

### ISSUE THREAD

**Issue by mightyiam** [maxogden/standard-format#13]
```sh
$ git clone wymeditor/wymeditor
$ cd wymeditor
$ standard-format -w
/home/shahar/.nvm/versions/node/v0.12.0/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3872
            throw e;
                  ^
Error: Line 295: Unexpected string
    at throwError (/home/shahar/.nvm/versions/node/v0.12.0/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:1156:21)
    at throwUnexpected (/home/shahar/.nvm/versions/node/v0.12.0/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:1195:13)
    at parseVariableIdentifier (/home/shahar/.nvm/versions/node/v0.12.0/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2081:13)
    at /home/shahar/.nvm/versions/node/v0.12.0/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3609:38
    at parseFunctionExpression (/home/shahar/.nvm/versions/node/v0.12.0/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2989:25)
    at /home/shahar/.nvm/versions/node/v0.12.0/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3609:38
    at parsePrimaryExpression (/home/shahar/.nvm/versions/node/v0.12.0/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:1535:24)
    at /home/shahar/.nvm/versions/node/v0.12.0/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3609:38
    at trackLeftHandSideExpressionAllowCall (/home/shahar/.nvm/versions/node/v0.12.0/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3504:61)
    at parsePostfixExpression (/home/shahar/.nvm/versions/node/v0.12.0/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:1703:20)
```

**Comment by jb55** [comment]
I was getting this when there was a syntax error in my code. perhaps we could make the error message a bit better

**Comment by mightyiam** [comment]
Thanks.
