### ISSUE TITLE
Unexpected token =>

### ISSUE THREAD

**Issue by chris9753** [maxogden/standard-format#137]
I'm getting an unexpected token error any ideas/help guys?
`
/home/chris9753/backend/node_modules/standard/node_modules/standard-format/node_modules/esformatter-semicolon-first/node_modules/espree/espree.js:5495
        throw e;
              ^
Error: Line 32: Unexpected token =>
    at throwError (/home/chris9753/backend/node_modules/standard/node_modules/standard-format/node_modules/esformatter-semicolon-first/node_modules/espree/espree.js:2070:17)
    at throwUnexpected (/home/chris9753/backend/node_modules/standard/node_modules/standard-format/node_modules/esformatter-semicolon-first/node_modules/espree/espree.js:2133:5)
    at expect (/home/chris9753/backend/node_modules/standard/node_modules/standard-format/node_modules/esformatter-semicolon-first/node_modules/espree/espree.js:2142:9)
    at parseArguments (/home/chris9753/backend/node_modules/standard/node_modules/standard-format/node_modules/esformatter-semicolon-first/node_modules/espree/espree.js:2916:13)
    at parseLeftHandSideExpressionAllowCall (/home/chris9753/backend/node_modules/standard/node_modules/standard-format/node_modules/esformatter-semicolon-first/node_modules/espree/espree.js:3001:20
)
    at parsePostfixExpression (/home/chris9753/backend/node_modules/standard/node_modules/standard-format/node_modules/esformatter-semicolon-first/node_modules/espree/espree.js:3044:12)
    at parseUnaryExpression (/home/chris9753/backend/node_modules/standard/node_modules/standard-format/node_modules/esformatter-semicolon-first/node_modules/espree/espree.js:3072:16)
    at parseBinaryExpression (/home/chris9753/backend/node_modules/standard/node_modules/standard-format/node_modules/esformatter-semicolon-first/node_modules/espree/espree.js:3196:12)
    at parseConditionalExpression (/home/chris9753/backend/node_modules/standard/node_modules/standard-format/node_modules/esformatter-semicolon-first/node_modules/espree/espree.js:3257:12)
    at parseAssignmentExpression (/home/chris9753/backend/node_modules/standard/node_modules/standard-format/node_modules/esformatter-semicolon-first/node_modules/espree/espree.js:3523:19)`

**Comment by bcomnes** [comment]
Can you post a snippet of code that triggers this?  esformatter stuff shouldnt blow up like this.

**Comment by chris9753** [comment]
`beforeEach(mochaAsync(async() => {
        //have to create a mock mongoose model for and user and bill

        user = await createUser("Jaypriochot");
        billing = await createUserBilling(user);
      }));
`

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
