### ISSUE TITLE
generator support

### ISSUE THREAD

**Issue by matthewmueller** [maxogden/standard-format#52]
would be nice to support generators, right now this is throwing:

```
Error: Line 111: Unexpected token *
    at createError (/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2306:21)
    at unexpectedTokenError (/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2381:13)
    at throwUnexpectedToken (/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2386:15)
```

**Comment by bcomnes** [comment]
I think we are waiting for upstream ES6 support, but I could be wrong.  Let me track down those details.

**Comment by bcomnes** [comment]
This might be tied to https://github.com/maxogden/standard-format/issues/35

**Comment by Flet** [comment]
This is now working with the latest `standard-format`!

Also I added a test to ensure its covered: https://github.com/maxogden/standard-format/commit/92193e0cc016123c1e2a7413ae1a2997b1255d29
