### ISSUE TITLE
Error and stack dump with "illegal return statement" :police_car:

### ISSUE THREAD

**Issue by pdehaan** [maxogden/standard-format#53]
```sh
$ standard-format --version
1.3.6
```

### Steps to reproduce:
1. Create a new file, _\_foo.js_, and paste the following content:

    ```js
var db = 'mysql'
if (db !== 'mysql') {
      return;
}
```
2. Save the file and run `$ standard-format -w _foo.js`.

### Actual results:
```
$ standard-format _foo.js

/Users/pdehaan/.npm-packages/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:5283
            throw e;
                  ^
Error: Line 3: Illegal return statement
    at createError (/Users/pdehaan/.npm-packages/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2306:21)
    at tolerateError (/Users/pdehaan/.npm-packages/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2342:17)
    at parseReturnStatement (/Users/pdehaan/.npm-packages/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:4168:13)
    at parseStatement (/Users/pdehaan/.npm-packages/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:4408:24)
    at parseStatementListItem (/Users/pdehaan/.npm-packages/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3716:16)
    at parseStatementList (/Users/pdehaan/.npm-packages/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3725:23)
    at parseBlock (/Users/pdehaan/.npm-packages/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3736:17)
    at parseStatement (/Users/pdehaan/.npm-packages/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:4377:20)
    at parseIfStatement (/Users/pdehaan/.npm-packages/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3907:22)
    at parseStatement (/Users/pdehaan/.npm-packages/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:4406:24)
```

### Expected results:
Not that.

**Comment by bcomnes** [comment]
We should probably handle that error.  Right now trying to format invalid JS results in errors.

**Comment by bcomnes** [comment]
Related: https://github.com/millermedeiros/esformatter/issues/206

**Comment by millermedeiros** [comment]
FYI, v0.7.0 of esformatter will allow `globalReturn` since we changed the parser to espree and [enabled this option by default](https://github.com/millermedeiros/esformatter/commit/f3b06d90b54bd3fed82cfbfdcc14ade2cb095506#diff-841daed463ab7befab0f2d50bf758bf9R73) - `return` outside of a function body won't throw errors.
