### ISSUE TITLE
Error with esprima.js

### ISSUE THREAD

**Issue by Sheraff** [maxogden/standard-format#72]
Some error I'm getting when simply running `standard-format` in a folder. Sadly I can't replicate: I have edited the file since then (without committing) and now it works fine. But it might have had something to do with a [structural thing](https://github.com/bcomnes/sublime-standard-format/issues/28).

```
/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:5283
            throw e;
                  ^
Error: Line 10: Unexpected token else
    at createError (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2306:21)
    at unexpectedTokenError (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2381:13)
    at throwUnexpectedToken (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2386:15)
    at consumeSemicolon (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2501:13)
    at parseReturnStatement (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:4175:17)
    at parseStatement (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:4408:24)
    at parseIfStatement (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3907:22)
    at parseStatement (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:4406:24)
    at parseStatementListItem (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3716:16)
    at parseFunctionSourceElements (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:4498:23)
```

I previously reported this [issue on feross/standard](https://github.com/feross/standard/issues/150).

**Comment by mmckegg** [comment]
Reproduce with:

```
test[0]
fail
```

Seems to occur anytime an array accessor is the last thing on a line.

Interestingly, when semicolons are present, it works fine:

```
test[0];
fail;
```
